controllers:
    resource: ../src/Controller/
    type: attribute

base:
    path: /
    controller: App\Controller\BaseController::base

user_notification:
    path: /user/notifications
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\UserController::notifications

user_auth:
    path: /auth
    controller: App\Controller\UserController::auth

user_reg:
    path: /reg
    controller: App\Controller\UserController::reg
